export enum SseConstants {
  SSE_AVATAR_IMPORT_SUCCESS = 'AVATAR_IMPORT_READY',
  SSE_AVATAR_IMPORT_FAILED = 'AVATAR_IMPORT_FAILED',
  SSE_AVATAR_EXPORT_SUCCESS = 'AVATAR_EXPORT_SUCCEEDED',
  SSE_AVATAR_EXPORT_FAILED = 'AVATAR_EXPORT_FAILED',
  EXTERNAL_SEARCH_COMPLETED = 'EXTERNAL_SEARCH_COMPLETED',
  SSE_DATASOURCE_UPDATED = 'DATASOURCE_UPDATED',
  SSE_AVATAR_CONNECTION_COMPLETE = 'AVATAR_CONNECTION_COMPLETE',
  SSE_AVATAR_LINKING_FAILED = 'AVATAR_LINKING_FAILED',
  SSE_AVATAR_LINKING_SUCCESSES = 'AVATAR_LINKING_SUCCEEDED',
  SSE_KEEP_ALIVE = 'KEEP_ALIVE',
}

export enum SseCrawlingErrors {
  NO_PROXY = 'NO_PROXY',
  BAD_PROXY = 'BAD_PROXY',
  TIMEOUT = 'TIMEOUT',
  UNSPECIFIED = 'UNSPECIFIED',
  ACCOUNT_BLOCKED = 'ACCOUNT_BLOCKED',
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS'
}

export const DATE_FORMATS = {
  parse: {
    dateInput: 'YYYY-MM-DD',
  },
  display: {
    dateInput: 'YYYY-MM-DD',
    monthYearLabel: 'MMM YYYY',
    dateA11yLabel: 'LL',
    monthYearA11yLabel: 'MMMM YYYY',
  },
};
